theme = "everforest_dark"

editor.bufferline = "multiple"

# disable arrow keys

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

# VsCode-like movement

C-j = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"]
C-k = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"]
C-h = "move_prev_word_start"
C-l = "move_next_word_start"

# Cursor shape between modes

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
